STRINGS = {
    "ru": {
        "welcome": "Добро пожаловать! Пожалуйста, выберите язык:",
        "get_name": "Введите ваше ФИО:",
        "get_phone": "Пожалуйста, напишите или поделитесь вашим номером телефона, нажав на кнопку ниже:",
        "share_phone": "Поделиться номером 📱",
        "main_menu": "Главное меню",
        "online_events": "Онлайн ивенты",
        "offline_events": "Оффлайн ивенты",
        "about_us": "О нас",
        "settings": "Настройки",
        "change_lang": "Выбор языка",
        "about_text": "Avlod Adventures Bot. Наши соцсети:",
        "no_events": "Список ивентов пуст.",
        "admin_pass": "Введите пароль администратора:",
        "admin_menu": "Панель администратора",
        "active_events": "Активные ивенты",
        "create_cat": "Создать категорию",
        "add_event": "Добавить ивент",
        "exit_admin": "Выйти из админки",
        "wrong_pass": "Неверный пароль!",
        "new_event_notify": "У нас новый ивент! Проверьте список.",
        "choose_cat": "Выберите категорию:",
        "send_img": "Отправьте картинку для ивента:",
        "send_desc": "Введите описание ивента:",
        "send_time": "Введите время проведения:",
        "send_date": "Введите дату проведения (например: 25 января 2026):",
        "send_capacity": "Введите максимальное количество участников (0 = без ограничений):",
        "event_saved": "Ивент успешно сохранен!",
        "cat_name": "Введите название категории:",
        "cat_saved": "Категория сохранена!",
        "curr_profile": "Ваш профиль:\nФИО: {name}\nТел: {phone}\nЯзык: {lang}",
        "change_name": "Изменить ФИО",
        "change_phone": "Изменить номер",
        "name_changed": "ФИО успешно изменено!",
        "phone_changed": "Номер успешно изменен!",
        "register": "Записаться ✅",
        "reg_success": "Вы успешно записались на ивент!",
        "already_reg": "Вы уже записаны на этот ивент.",
        "confirm_reg": "Ваши данные для регистрации:\n\n👤 ФИО: {name}\n📞 Телефон: {phone}\n\nВсе верно?",
        "confirm_btn": "Да, записаться ✅",
        "edit_name_btn": "Изменить ФИО",
        "edit_phone_btn": "Изменить номер",
        "send_location": "Отправьте локацию ивента (геолокацию):",
        "location_invalid": "Пожалуйста, отправьте локацию через вложение (скрепка -> геопозиция)."
    },
    "uz": {
        "welcome": "Xush kelibsiz! Iltimos, tilni tanlang:",
        "get_name": "To'liq ismingizni kiriting (FIO):",
        "get_phone": "Iltimos, telefon raqamingizni yozing yokipastdagi tugmani bosish orqali yuboring:",
        "share_phone": "Raqamni yuborish 📱",
        "main_menu": "Asosiy menyu",
        "online_events": "Onlayn tadbirlar",
        "offline_events": "Offlayn tadbirlar",
        "about_us": "Biz haqimizda",
        "settings": "Sozlamalar",
        "change_lang": "Tilni tanlash",
        "about_text": "Avlod Adventures Bot! Bizning ijtimoiy tarmoqlar:",
        "no_events": "Tadbirlar ro'yxati bo'sh.",
        "admin_pass": "Admin parolini kiriting:",
        "admin_menu": "Admin paneli",
        "active_events": "Faol tadbirlar",
        "create_cat": "Kategoriya yaratish",
        "add_event": "Tadbir qo'shish",
        "exit_admin": "Admindan chiqish",
        "wrong_pass": "Noto'g'ri parol!",
        "new_event_notify": "Bizda yangi tadbir! Ro'yxatni tekshiring.",
        "choose_cat": "Kategoriyani tanlang:",
        "send_img": "Tadbir uchun rasm yuboring:",
        "send_desc": "Tadbir tavsifini kiriting:",
        "send_time": "O'tkazilish vaqtini kiriting:",
        "send_date": "O'tkazilish sanasini kiriting (masalan: 25 yanvar 2026):",
        "send_capacity": "Maksimal ishtirokchilar sonini kiriting (0 = cheklovsiz):",
        "event_saved": "Tadbir muvaffaqiyatli saqlandi!",
        "cat_name": "Kategoriya nomini kiriting:",
        "cat_saved": "Kategoriya saqlandi!",
        "curr_profile": "Sizning profilingiz:\nFIO: {name}\nTel: {phone}, Til: {lang}",
        "change_name": "FIO o'zgartirish",
        "change_phone": "Raqamni o'zgartirish",
        "name_changed": "FIO muvaffaqiyatli o'zgartirildi!",
        "phone_changed": "Raqam muvaffaqiyatli o'zgartirildi!",
        "register": "Ro'yxatdan o'tish ✅",
        "reg_success": "Siz muvaffaqiyatli ro'yxatdan o'tdingiz!",
        "already_reg": "Siz allaqachon ro'yxatdan o'tgansiz.",
        "confirm_reg": "Ro'yxatdan o'tish ma'lumotlaringiz:\n\n👤 FIO: {name}\n📞 Tel: {phone}\n\nMa'lumotlar to'g'rimi?",
        "confirm_btn": "Ha, ro'yxatdan o'tish ✅",
        "edit_name_btn": "FIO o'zgartirish",
        "edit_phone_btn": "Raqamni o'zgartirish",
        "send_location": "Tadbir joylashuvini yuboring (geolokatsiya):",
        "location_invalid": "Iltimos, joylashuvni ilova orqali yuboring."
    },
    "en": {
        "welcome": "Welcome! Please choose a language:",
        "get_name": "Enter your full name:",
        "get_phone": "Please share your phone number by clicking the button or write it below:",
        "share_phone": "Share phone 📱",
        "main_menu": "Main Menu",
        "online_events": "Online Events",
        "offline_events": "Offline Events",
        "about_us": "About Us",
        "settings": "Settings",
        "change_lang": "Choose language",
        "about_text": "Avlod AdventuresBot! Our social media:",
        "no_events": "The event list is empty.",
        "admin_pass": "Enter admin password:",
        "admin_menu": "Admin Panel",
        "active_events": "Active Events",
        "create_cat": "Create Category",
        "add_event": "Add Event",
        "exit_admin": "Exit Admin",
        "wrong_pass": "Wrong password!",
        "new_event_notify": "We have a new event! Check the list.",
        "choose_cat": "Choose a category:",
        "send_img": "Send an image for the event:",
        "send_desc": "Enter event description:",
        "send_time": "Enter event time:",
        "send_date": "Enter event date (e.g., January 25, 2026):",
        "send_capacity": "Enter maximum number of participants (0 = unlimited):",
        "event_saved": "Event saved successfully!",
        "cat_name": "Enter category name:",
        "cat_saved": "Category saved!",
        "curr_profile": "Your profile:\nName: {name}\nPhone: {phone}\nLanguage: {lang}",
        "change_name": "Change Name",
        "change_phone": "Change Phone",
        "name_changed": "Name updated successfully!",
        "phone_changed": "Phone updated successfully!",
        "register": "Register ✅",
        "reg_success": "You have successfully registered for the event!",
        "already_reg": "You are already registered for this event.",
        "confirm_reg": "Your registration details:\n\n👤 Name: {name}\n📞 Phone: {phone}\n\nIs this correct?",
        "confirm_btn": "Yes, register ✅",
        "edit_name_btn": "Change Name",
        "edit_phone_btn": "Change Phone",
        "send_location": "Send event location (geolocation):",
        "location_invalid": "Please send location via attachment."
    }
}
